### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by miharu0626** [miharu0626/furima_28749#15]
- 私のフリマアプリのURL 
https://furima-28749.herokuapp.com/

- Basic認証のIDとパスワード
【ID】admin
【PW】2222

- 出品者用のメールアドレスとパスワード
いちご
【メールアドレス】test@yahoo.co.jp
【PW】m111111

- 購入者用のメールアドレスとパスワード
みかん
【メールアドレス】test2@yahoo.co.jp
【PW】m111111

- 購入用カードの番号・期限・セキュリティコード
【カードの番号】4242424242424242
【期限】12/24
【セキュリティコード】123

**Comment by keisukekodama** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします**。
